### ISSUE TITLE
No input validation for pull

### ISSUE THREAD

**Issue by Scoder12** [sugarfi/ReplitCLI#7]
```
$ replitcli pull only1arg
replitcli/index.js:138
        if (err) throw err;
                 ^

[Error: ENOENT: no such file or directory, mkdir ''] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: ''
}
```

**Comment by Scoder12** [comment]
This would be fixed by #5

**Comment by sugarfi** [comment]
I'm only gonna reply to this one issue since there's only 12 of them. I don't really update this project anymore, having other stuff to work on - I'd be happy to transfer ownership to you so you can fix these things yourself!

**Comment by Scoder12** [comment]
To be honest I would rather start from scratch using typescript and make a new library, I just wanted to make sure that it was okay with you.

**Comment by sugarfi** [comment]
Yeah, that would be fine. I think I'll go ahead and archive this repo - I don't plan on working on it anymore.
